[package]
name = "showcase-fft"
version = "0.1.0"
edition = "2024"

[dependencies]
snmalloc-rs = { version = "0.3", features = ["lto"] }

[lib]
name = "fft"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
